spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

project:
  name: api-uber-chargers
  version: 1.0.0
  description: API rest to check available chargers from electric uber.

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    version: ${project.version}

spring:
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop
  
logging:
  file: api-uber-chargers.log
  org.hibernate: INFO
